export const TELEGRAM_NOTIFICATION_CONFIG_KEYS = Object.freeze({
  enabled: 'TELEGRAM_OUTBOUND_NOTIFICATIONS_ENABLED',
  miniAppUrl: 'TELEGRAM_MINI_APP_URL',
} as const);

export const TELEGRAM_NOTIFICATION_POLL_INTERVAL_MILLISECONDS = 1_000;
export const TELEGRAM_NOTIFICATION_REQUEST_TIMEOUT_MILLISECONDS = 5_000;
export const TELEGRAM_NOTIFICATION_VISIBILITY_LEASE_SECONDS = 15;
